// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace TagGameplayTags
{
	// Declare all of the custom native tags that Tag will use

	// Movement Abilities
	TAG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Dash);
	TAG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Jump);
	TAG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Slide);
	TAG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Crouch);
	TAG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Sprint);

	// Tagging Abilities
	TAG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_TagPassive);
	TAG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Tag);
	TAG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Tag_Cooldown);
	TAG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Tag_Disabled);
	TAG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_SelfTag);
	TAG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ApplyTag);

	// Gameplay Effects
	TAG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_SpeedBuff);
	TAG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_StaminaRegen);
	TAG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_TagCooldown);
	TAG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_Tagged);

	// Gameplay Cues
	TAG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Hero_Sprint);
	TAG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Tagged);

	// States
	TAG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_CouldTagSomeone);
	TAG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Crouching);
	TAG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);
	TAG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Jumping);
	TAG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Sliding);
	TAG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Sprinting);
	TAG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Tagged);
	TAG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Untagged);

	// Events
	TAG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_ChooseTagger);
	TAG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Tag);
	TAG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_TagReceived);
	TAG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_TagGiven);

	
};
